# Generated by Django 4.0 on 2024-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_order_status_order_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
